apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apply-manifests
spec:
  workspaces:
  - name: source
  params:
    - name: iac_dir
      description: This directory contains GitRepository and Kustomization flux ressources.
      type: string
      default: "iac"
  steps:
    - name: apply
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo Applying manifests in $(inputs.params.flux_manifests) directory
          oc apply -f $(inputs.params.iac_dir)
          echo -----------------------------------
