kind: Secret
apiVersion: v1
metadata:
  name: docker-credentials
data:
  config.json: >-
    eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJqb3NlcGhhc3NpZ2EiLCJwYXNzd29yZCI6IlJldXNzaXI3NSIsImVtYWlsIjoiam9zZXBoLmFzc2lnYUBnbWFpbC5jb20iLCJhdXRoIjoiYW05elpYQm9ZWE56YVdkaE9sSmxkWE56YVhJM05RPT0ifX19

