apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: vote-app-api
spec:
  pipelineRef:
    name: build-and-deploy
  params:
    - name: git-url
      value: git@ssh.dev.azure.com:v3/josephassiga/migration-factory/pipelines-vote-api
    - name: IMAGE
      value: josephassiga/vote-app-api
    - name: deployment-name
      value: vote-app-api
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: '500Mi'
    - name: azure-repo-credentials-workspace
      secret:
        secretName: git-credentials
    - name: dockerconfig-workspace
      secret:
        secretName: docker-credentials
